### ISSUE TITLE
There is an option to force the auto download inside Jdownloader and downlolad always on Jdownlader when we click on a link?

### ISSUE THREAD

**Issue by ovnis82** [pouriap/Grabby#5]
Hello,

There is an option to force the auto download inside Jdownloader? Actually, we have to go to Jdownloader to click "download" if we want download files ?

Inside options;, my default download manager is Jdownload.

**Comment by siamak2** [comment]
Jdownloader has the ability to auto start downloads but it's disabled and it's hard coded:
https://github.com/pouriap/Firefox-DownloadGrab/blob/86d7fef20c075efb6b3133922df94911180e128a/modules/dmhelper.js#L108

@pouriap can you add an option to options page for auto starting downloads?

**Comment by pouriap** [comment]
I can do that but you have to wait.

Currently I'm working on the addon and I've refractored it quite a bit and am adding the media grab feature too. The code is very different that the current one and I can't release a new version until it's all done because it is incompatible with the current native host too. So everything is gonna change.

If everything goes right I might be able to release a pre-alpha version in a couple weeks which has this feature in it. But more importantly it will grab media!

**Comment by pouriap** [comment]
Option added in version 0.61.3a
